# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-07 20:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_auto_20170908_0245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='vote',
        ),
        migrations.AddField(
            model_name='question',
            name='vote',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='questions.Vote'),
        ),
    ]
