# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-07 21:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_auto_20170908_0255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='vote',
        ),
        migrations.AddField(
            model_name='question',
            name='vote',
            field=models.ManyToManyField(to='questions.Vote'),
        ),
    ]
