# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-08 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0008_auto_20170908_0316'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='downvote',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vote',
            name='upvote',
            field=models.BooleanField(default=False),
        ),
    ]
