# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-08 14:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0009_auto_20170908_1514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='value',
        ),
    ]
