# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-08 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0010_remove_vote_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='total',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
