# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-08 19:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0012_auto_20170909_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='total',
            field=models.IntegerField(),
        ),
    ]
